version: '3'
services:
  db2:
    #image: ibmcom/db2:11.5.6.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db2
    restart: always
    #privileged: true
    ipc: host
    cap_add:
      - IPC_OWNER
    env_file:
      - ./db2.env
    volumes:
      - ./node/db:/database
    ports:
      - 50000:50000
      - 50100:50100